#!/usr/bin/env bash
# Install the pre-commit hook that runs tools/scan-secrets.sh on every commit. Run once after cloning.
set -euo pipefail
root=$(git rev-parse --show-toplevel)
hook=$(git -C "$root" rev-parse --git-path hooks/pre-commit)
cat > "$hook" <<'HOOK'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh - refuses commits containing addresses or seed-like text.
set -euo pipefail
exec "$(git rev-parse --show-toplevel)/tools/scan-secrets.sh" --staged
HOOK
chmod 755 "$hook"
echo "pre-commit hook installed: $hook"
